server:
  port: 8813
  tomcat:
    uri-encoding: UTF-8
spring:
  security:
    user:
      name: admin
      password: admin123
  activiti:
    check-process-definitions: false
    history-level: full
  datasource:
    url: jdbc:mysql://localhost:3306/bpm
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  thymeleaf:
    cache: false
    prefix: classpath:/static/
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
